version: '3'

services:

  fluentd:
    restart: always
    hostname: fluentd
    container_name: fluentd
    image: crunchgeek/fluentd:latest
    env_file: .env
    ports:
      - "24224:24224"
      - "24224:24224/udp"
