version: '3'

services:

  fluentd:
    restart: always
    hostname: fluentd
    container_name: fluentd
    image: crunchgeek/fluentd:latest
    environment:
      - GC_PROJECT=crunch-geek
      - GC_DATASET=logs
      - GC_TABLE_NGINX=nginx
      - GC_TABLE_NGINX_ERRORS=nginx_errors
      - GC_TABLE_PHP70=php70
      - GC_TABLE_PHP56=php56
      - GC_TABLE_PHP53=php53
      - GC_TABLE_NEWRELIC=newrelic
      - GC_TABLE_WATCHTOWER=watchtower
    ports:
      - "24224:24224"
      - "24224:24224/udp"
